# Generated by Django 2.0.6 on 2021-08-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('pk_marcas', models.AutoField(primary_key=True, serialize=False)),
                ('nike', models.CharField(max_length=80)),
                ('addidas', models.CharField(max_length=80)),
                ('puma', models.CharField(max_length=80)),
                ('converse', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='tallas',
            fields=[
                ('pk_tallas', models.AutoField(primary_key=True, serialize=False)),
                ('adultos', models.CharField(max_length=80)),
                ('niños', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fk_product',
        ),
        migrations.DeleteModel(
            name='invoice',
        ),
    ]
