# Generated by Django 2.0.6 on 2021-09-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210907_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='addidas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='converse',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='nike',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='puma',
            field=models.IntegerField(),
        ),
    ]
