# Generated by Django 2.0.6 on 2021-09-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210907_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.URLField(default='https://i.imgur.com/llmXU3a.jpg', max_length=800),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.URLField(default='https://i.imgur.com/KDHLAjk.jpg', max_length=800),
        ),
    ]
