# Generated by Django 2.0.6 on 2021-09-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210908_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.URLField(default='https://i.imgur.co m/KDHLAjk.jpg', max_length=800),
        ),
    ]
