# Generated by Django 2.0.6 on 2021-09-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210908_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.URLField(default='https://i.imgur.co m/KDHLAjk.jpg', max_length=800),
        ),
    ]
